// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAwuTILm92Eby1ETpAigNkQh_ftC8c7zE',
    appId: '1:877491921811:web:e3c7230e5626208e37fe66',
    messagingSenderId: '877491921811',
    projectId: 'anddumpfirebase1',
    authDomain: 'anddumpfirebase1.firebaseapp.com',
    databaseURL: 'https://anddumpfirebase1.firebaseio.com',
    storageBucket: 'anddumpfirebase1.appspot.com',
    measurementId: 'G-DWGG75BVE4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPXBE14sf2uzXKKBgfyCigtHKJmq500Vw',
    appId: '1:877491921811:android:caa24add043799ad37fe66',
    messagingSenderId: '877491921811',
    projectId: 'anddumpfirebase1',
    databaseURL: 'https://anddumpfirebase1.firebaseio.com',
    storageBucket: 'anddumpfirebase1.appspot.com',
  );
}
